title: Alexandra Hogan PhD
author: Alexandra B Hogan
email: alexandra.hogan@unsw.edu.au
description: > # this means to ignore newlines until "baseurl:"
  Personal academic website for Alexandra B Hogan PhD.

# social links
twitter_username: alexandrabh # DO NOT include the @ character, or else the build will fail!
github_username:  abhogan # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
